/* auto-generated by @napi-rs/cli (partial — supplemented by hand for full type safety) */

export interface RawEvent {
  chain: string
  txHash: string
  blockNumber: number
  blockTimestamp: number
  logIndex: number
  address: string
  topics: string[]
  /** hex-encoded data with 0x prefix */
  data: string
}

export interface DecodedEvent {
  schema: string
  schemaVersion: number
  chain: string
  txHash: string
  blockNumber: number
  blockTimestamp: number
  logIndex: number
  address: string
  /** key → decoded value */
  fields: Record<string, NormalizedValue>
  /** keccak256 of topics[0] */
  fingerprint: string
  /** fields that failed to decode */
  decodeErrors: Record<string, string>
}

export interface DecodedCall {
  functionName: string
  /** 4-byte selector as hex "0xaabbccdd" */
  selector: string | null
  /** positional inputs as [name, value] pairs */
  inputs: Array<[string, NormalizedValue]>
  decodeErrors: Record<string, string>
}

export type NormalizedValue =
  | { type: 'uint'; value: number | bigint }
  | { type: 'biguint'; value: string }
  | { type: 'int'; value: number | bigint }
  | { type: 'bigint'; value: string }
  | { type: 'bool'; value: boolean }
  | { type: 'bytes'; value: number[] }
  | { type: 'str'; value: string }
  | { type: 'address'; value: string }
  | { type: 'hash256'; value: string }
  | { type: 'timestamp'; value: number }
  | { type: 'array'; value: NormalizedValue[] }
  | { type: 'tuple'; value: Array<[string, NormalizedValue]> }
  | { type: 'null' }

export interface TypedData {
  types: Record<string, Array<{ name: string; type: string }>>
  primaryType: string
  domain: Record<string, unknown>
  message: Record<string, unknown>
}

export interface BatchDecodeResult {
  events: DecodedEvent[]
  errors: Array<{ index: number; error: string }>
}

// ─── MemoryRegistry ───────────────────────────────────────────────────────────

export declare class MemoryRegistry {
  constructor()
  /** Load schemas from a CSDL YAML string. Returns number of schemas loaded. */
  loadCsdl(csdl: string): number
  /** Load schemas from a .csdl file path. */
  loadFile(path: string): number
  /** Load all .csdl files from a directory. */
  loadDirectory(path: string): number
  readonly schemaCount: number
  schemaNames(): string[]
}

// ─── EvmDecoder ───────────────────────────────────────────────────────────────

export declare class EvmDecoder {
  constructor()
  decodeEvent(raw: RawEvent, registry: MemoryRegistry): DecodedEvent
  fingerprint(raw: RawEvent): string
  decodeBatch(raws: RawEvent[], registry: MemoryRegistry): BatchDecodeResult
}

// ─── EvmCallDecoder ───────────────────────────────────────────────────────────

export declare class EvmCallDecoder {
  /** Create from standard Ethereum ABI JSON */
  static fromAbiJson(abiJson: string): EvmCallDecoder
  /** Decode calldata (hex string with 0x prefix) */
  decodeCall(calldata: string, functionName?: string | null): DecodedCall
  functionNames(): string[]
  selectorFor(functionName: string): string | null
}

// ─── EvmEncoder ───────────────────────────────────────────────────────────────

export declare class EvmEncoder {
  /** Create from standard Ethereum ABI JSON */
  static fromAbiJson(abiJson: string): EvmEncoder
  /** Encode a function call. args is JSON array of NormalizedValues. Returns 0x-prefixed hex. */
  encodeCall(functionName: string, argsJson: string): string
}

// ─── Eip712Parser ─────────────────────────────────────────────────────────────

export declare class Eip712Parser {
  constructor()
  parse(json: string): TypedData
  domainSeparator(json: string): string
}
